name: CI Semillero

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: "elianazamo07/devco-videojuegos"
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v1.4.4
      with:
        java-version: "17"
    - name: Get Time
      id: time
      uses: nanzm/get-time-action@master
      with:
        timeZone: UTC+8
        format: 'YYYY-MM-DD-HH-mm-ss'
    - name: Usage
      env:
        TIME: "${{ steps.time.outputs.time }}"
      run: |
        echo $TIME
    - name: Compile and build maven
      run: mvn --batch-mode --update-snapshots package
    - name: Unit test maven
      run: mvn test
    - name: Generate code coverage report
      run:  chmod +x mvnw; ./mvnw jacoco:report
    - name: SonarCloud Scan
      run: ./mvnw -B verify sonar:sonar -Dsonar.projectKey=elianazamora07_devco-videojuegos -Dsonar.organization=elianazamora07 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    - name: SonarQube Quality Gate Check
      uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      with:
        scanMetadataReportFile: target/sonar/report-task.txt
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Buildx and Push
        uses: docker/setup-buildx-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}-${{ env.TIME }}:latest
